export enum EAction {
  SET_HELLO_WORLD = "SET_HELLO_WORLD",
  INCREMENT_TIME_DAYS = "INCREMENT_TIME_DAYS",
  SET_MONEY_AMOUNT = "SET_MONEY_AMOUNT",
  SET_MODAL_DATA = "SET_MODAL_DATA",
  SET_CLOSE_MODAL = "SET_CLOSE_MODAL",
  SET_CAR_DATA = "SET_CAR_DATA",
  SET_ALL_NOTIFICATION_DATA = "SET_ALL_NOTIFICATION_DATA",
  SET_NEW_NOTIFICATION = "SET_NEW_NOTIFICATION",
}
