export enum EAction {
  SET_IS_GAME_RUNNING = "SET_IS_GAME_RUNNING",
  SET_GAME_STATUS = "SET_GAME_STATUS",
  SET_HAS_UNDERSTOOD_INTRO = "SET_HAS_UNDERSTOOD_INTRO",
  INCREMENT_TIME_DAYS = "INCREMENT_TIME_DAYS",
  SET_MONEY_AMOUNT = "SET_MONEY_AMOUNT",
  SET_MODAL_DATA = "SET_MODAL_DATA",
  SET_CLOSE_MODAL = "SET_CLOSE_MODAL",
  SET_ALL_NOTIFICATION_DATA = "SET_ALL_NOTIFICATION_DATA",
  SET_NEW_NOTIFICATION = "SET_NEW_NOTIFICATION",
}
